//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     코드가 다시 생성될 경우 이 파일이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class MainScreen
{
	public virtual void Refreshscreen(object pixel px)
	{
		throw new System.NotImplementedException();
	}

	public virtual int getFPS()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ShowText(string Text,Pixel px)
	{
		throw new System.NotImplementedException();
	}

	public virtual void SetDistScreen(Screen sr)
	{
		throw new System.NotImplementedException();
	}

}

