//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     코드가 다시 생성될 경우 이 파일이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class AI : Player
{
	public virtual void RequestDownMove(string code)
	{
		throw new System.NotImplementedException();
	}

	public virtual void RequestLeftMove(string code)
	{
		throw new System.NotImplementedException();
	}

	public virtual void RequestRightMove(string code)
	{
		throw new System.NotImplementedException();
	}

	public virtual void RequestUpMove(string code)
	{
		throw new System.NotImplementedException();
	}

	public virtual void RequestStop(string code)
	{
		throw new System.NotImplementedException();
	}

	public virtual void RequestSkill(string code,string code2)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Connect(string code, String cellname,Screen sr)
	{
		throw new System.NotImplementedException();
	}

}

