//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     코드가 다시 생성될 경우 이 파일이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Bullet : MoveableObject
{
	public virtual string Code
	{
		get;
		set;
	}

	public virtual LinkedList<Skill> Skills
	{
		get;
		set;
	}

	public virtual int HP
	{
		get;
		set;
	}

	public virtual Pixel Location
	{
		get;
		set;
	}

	public virtual string cellname
	{
		get;
		set;
	}

	public virtual bool Collided
	{
		get;
		set;
	}

	public abstract void DeleteSkill(Skill sk);

	public abstract void Disable();

	public abstract void DownMove();

	public abstract void GiveSkill(Skill sk);

	public abstract void IfCollision(MoveableObject Mo);

	public abstract void Kill();

	public abstract void LeftMove();

	public abstract void RightMove();

	public abstract void Stop();

	public abstract void UpMove();

	public virtual void EffectSkill(string code)
	{
		throw new System.NotImplementedException();
	}

}

