//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     코드가 다시 생성될 경우 이 파일이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface Player 
{
	void RequestDownMove(object string code);

	void RequestLeftMove(object string code);

	void RequestRightMove(object string code);

	void RequestUpMove(object string code);

	void RequestStop(object string code);

	void RequestSkill(object string code1, object string code2);

	void Connect(object string code, object String cellname, object Screen sr));

}

