//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     코드가 다시 생성될 경우 이 파일이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class RedbloodCell : MoveableObject
{
	public virtual object string Code
	{
		get;
		set;
	}

	public virtual object LinkedList<Skill> Skills;
	{
		get;
		set;
	}

	public virtual object int HP
	{
		get;
		set;
	}

	public virtual object Pixel Location
	{
		get;
		set;
	}

	public virtual object string cellname
	{
		get;
		set;
	}

	public virtual object bool Collided
	{
		get;
		set;
	}

	public abstract void DeleteSkill(object Skill sk);

	public abstract void Disable();

	public abstract void DownMove();

	public abstract void GiveSkill(object Skill sk);

	public abstract void IfCollision(object MoveableObject Mo);

	public abstract void Kill();

	public abstract void LeftMove();

	public abstract void RightMove();

	public abstract void Stop();

	public abstract void UpMove();

	public virtual void EffectSkill(object string code)
	{
		throw new System.NotImplementedException();
	}

}

