//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     코드가 다시 생성될 경우 이 파일이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface Screen 
{
	void AddBackground(Image bitmap);

	void ChangeBackground(Image bitmap);

	void getObjectList();

	void getBackground();

	void getMessage();

	void ScreenOnLoad();

	void ScreenOff();

	void AddObject(String Code, Pixel px);

	void RemoveObject(String Code);

	void MoveObject(String Code);

}

